# Generated by Django 3.2.8 on 2022-06-07 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('Content', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=125)),
                ('Email_adress', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(default='user.jpg', upload_to='profile_pics')),
                ('Bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
