# Generated by Django 3.2.8 on 2022-06-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Frontend'), ('2', 'Backend'), ('3', 'Fullstack')], max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'Draft'), ('2', 'Published')], max_length=10),
        ),
    ]
